[package]
name = "imgal"
version = "0.1.0"
authors = ["Edward Evans"]
edition = "2024"

[lib]
name = "imgal"
crate-type = ["rlib"]

[dependencies]
ndarray = { version = "0.16.1", features = ["rayon"] }
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
rustfft = "6.3"
