[package]
name = "imgal_python"
version = "0.1.0"
authors = ["Edward Evans"]
edition = "2024"

[lib]
name = "imgal_python"
crate-type = ["cdylib"]

[dependencies]
imgal_core = { path = "../imgal_core" }
pyo3 = { version = "0.24.1", features = ["extension-module"] }
